#!/bin/sh
# File generated by ocamlbuild

cd /Users/candy/code/ocaml/DPPL/mycode/lambdaLF

rm -f core.cmi
rm -f core.cmo
rm -f syntax.cmi
rm -f syntax.cmo
# Also clean the script itself
rm -f /Users/candy/code/ocaml/DPPL/mycode/lambdaLF/_build/sanitize.sh
